# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requisitos_razon_social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'operario_razon_social_requisitos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Razon_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos_RS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='razon_social',
            name='requisitos',
            field=models.ManyToManyField(related_name='razon_social_requisitos', to='operario.Requisitos_RS'),
        ),
    ]
