# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=12, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('nit', models.CharField(blank=True, max_length=12, null=True)),
                ('ruta', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('documento_legal', models.TextField(blank=True, null=True)),
                ('digital', models.FileField(blank=True, null=True, upload_to='legal')),
            ],
        ),
        migrations.CreateModel(
            name='Razon_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rep_Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_r', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio_r', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_activo', models.BooleanField(default=False)),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operario.Operario')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos_RS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='razon_social',
            name='requisitos',
            field=models.ManyToManyField(to='operario.Requisitos_RS'),
        ),
        migrations.AddField(
            model_name='operario',
            name='razon_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operario.Razon_Social'),
        ),
    ]
