# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-31 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razon_social',
            name='requisitos',
            field=models.ManyToManyField(related_name='razon_social_requisitos', to='operario.Requisitos_RS'),
        ),
    ]
