# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operario', '0002_auto_20181231_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisitos_razon_social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'operario_razon_social_requisitos',
                'managed': False,
            },
        ),
    ]
