# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignar_Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validez', models.IntegerField(blank=True, default=1, null=True)),
                ('gestion', models.IntegerField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('valida_del', models.DateField(blank=True, null=True)),
                ('valida_al', models.DateField(blank=True, null=True)),
                ('tiene_tarjeta', models.BooleanField(default=False)),
                ('caducado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(blank=True, default='EXTENSION TARJETA DE OPERACION INTERPROVINCIAL', max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('num_fojas', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True, default='EXTENSION DE TARJETAS DE OPERACIONES', null=True)),
                ('baja_observacion', models.TextField(blank=True, null=True)),
                ('tiene_orden', models.BooleanField(default=False)),
                ('finalizar', models.BooleanField(default=False)),
                ('vigente', models.BooleanField(default=True)),
                ('asignar_v', models.ManyToManyField(related_name='tramite', through='tramite.Asignar_Vehiculo', to='tecnico.Vehiculo_Nuevo')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo')),
            ],
            options={
                'permissions': (('administrar_tramite', 'Puede administrar tramites'),),
            },
        ),
        migrations.AddField(
            model_name='asignar_vehiculo',
            name='tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignar', to='tramite.Tramite'),
        ),
        migrations.AddField(
            model_name='asignar_vehiculo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asig_vehiculo', to='tecnico.Vehiculo_Nuevo'),
        ),
    ]
