# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(blank=True, default='EXTENSION TARJETA DE OPERACION INTERPROVINCIAL', max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('solicitante', models.CharField(blank=True, max_length=200, null=True)),
                ('num_fojas', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('obserbaciones', models.CharField(blank=True, default='EXTENSION DE TARJETAS DE OPERACIONES', max_length=50, null=True)),
                ('obserbacion2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
