# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-05 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_auto_20190205_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tramite',
        ),
    ]
