# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-05 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnico', '0020_auto_20190130_1106'),
        ('tramite', '0003_delete_tramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(blank=True, default='EXTENSION TARJETA DE OPERACION INTERPROVINCIAL', max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('num_fojas', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True, default='EXTENSION DE TARJETAS DE OPERACIONES', null=True)),
                ('baja_observacion', models.TextField(blank=True, null=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo')),
            ],
        ),
    ]
