# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-21 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0026_informe_ans_tecnico'),
        ('tramite', '0004_tramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignar_Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validez', models.IntegerField(blank=True, default=1, null=True)),
                ('gestion', models.IntegerField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignar', to='tramite.Tramite')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asig_vehiculo', to='tecnico.Vehiculo_Nuevo')),
            ],
        ),
        migrations.AddField(
            model_name='tramite',
            name='checklist',
            field=models.ManyToManyField(related_name='tramite', through='tramite.Asignar_Vehiculo', to='tecnico.Vehiculo_Nuevo'),
        ),
    ]
