# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-01 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_auto_20190221_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='tiene_orden',
            field=models.BooleanField(default=False),
        ),
    ]
