# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0007_tramite_tiene_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_vehiculo',
            name='valida_al',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignar_vehiculo',
            name='valida_del',
            field=models.DateField(blank=True, null=True),
        ),
    ]
