# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-14 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0008_auto_20190312_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_vehiculo',
            name='tiene_tarjeta',
            field=models.BooleanField(default=False),
        ),
    ]
