# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-14 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0009_asignar_vehiculo_tiene_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='finalizar',
            field=models.BooleanField(default=False),
        ),
    ]
