# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-11 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0010_tramite_finalizar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
