# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-03 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0011_tramite_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_vehiculo',
            name='caducado',
            field=models.BooleanField(default=False),
        ),
    ]
