# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-05 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0012_asignar_vehiculo_caducado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramite',
            options={'permissions': (('administrar_tramite', 'Puede administrar tramites'),)},
        ),
    ]
