# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-11 13:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisitos_vehiculo_tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tecnico_tipo_vehiculo_requisitos_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checklist_Operario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cumple', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist_Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cumple', models.BooleanField(default=True)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docs_Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('cite', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero_ra', models.IntegerField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('administrar_doc_legal', 'Puede administrar documentos legales'),),
            },
        ),
        migrations.CreateModel(
            name='Fotos_Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='fotos-vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('ans_tecnico', models.TextField(blank=True, null=True)),
                ('concluciones', models.TextField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Informe')),
            ],
        ),
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('licencia', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cancelado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nombre_ente', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_ente', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_repr', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta_solicitada', models.TextField(blank=True, null=True)),
                ('cantidad_tarjetas', models.IntegerField(blank=True, null=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('fenecio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operador_Nuevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_registro', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=12, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('nit', models.CharField(blank=True, max_length=12, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('documento_legal', models.TextField(blank=True, null=True)),
                ('digital', models.FileField(blank=True, null=True, upload_to='legal')),
                ('vigente', models.BooleanField(default=True)),
                ('es_nuevo', models.BooleanField(default=True)),
                ('en_tramite', models.BooleanField(default=True)),
                ('checklist', models.ManyToManyField(related_name='operario', through='tecnico.Checklist_Operario', to='operario.Requisitos_RS')),
                ('razon_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operario.Razon_Social')),
            ],
            options={
                'permissions': (('administrar_operador', 'Puede administrar al operador'), ('verificar', 'Puede verificar'), ('administrador', 'Puede administrar todo')),
            },
        ),
        migrations.CreateModel(
            name='Requisitos_Vehi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(blank=True, max_length=100, null=True)),
                ('hora', models.CharField(blank=True, max_length=100, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('requisitos_v', models.ManyToManyField(to='tecnico.Requisitos_Vehi')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo_Nuevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(blank=True, max_length=75, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=75, null=True)),
                ('marca', models.CharField(blank=True, max_length=75, null=True)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('chasis', models.CharField(blank=True, max_length=75, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=75, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('es_nuevo', models.BooleanField(default=True)),
                ('renovando', models.BooleanField(default=False)),
                ('dar_baja', models.BooleanField(default=False)),
                ('checklist', models.ManyToManyField(related_name='vehiculo', through='tecnico.Checklist_Vehiculo', to='tecnico.Requisitos_Vehi')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='tecnico.Operador_Nuevo')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Tipo_Vehiculo')),
            ],
            options={
                'permissions': (('emitir_infraccion', 'Puede emitir infraccion'),),
            },
        ),
        migrations.AddField(
            model_name='nota',
            name='operador_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo'),
        ),
        migrations.AddField(
            model_name='infraccion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Vehiculo_Nuevo'),
        ),
        migrations.AddField(
            model_name='informe',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo'),
        ),
        migrations.AddField(
            model_name='fotos_vehiculo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tecnico.Vehiculo_Nuevo'),
        ),
        migrations.AddField(
            model_name='docs_legal',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo'),
        ),
        migrations.AddField(
            model_name='checklist_vehiculo',
            name='requisitos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='tecnico.Requisitos_Vehi'),
        ),
        migrations.AddField(
            model_name='checklist_vehiculo',
            name='vehiculo_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_vehiculo', to='tecnico.Vehiculo_Nuevo'),
        ),
        migrations.AddField(
            model_name='checklist_operario',
            name='operador_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_operario', to='tecnico.Operador_Nuevo'),
        ),
        migrations.AddField(
            model_name='checklist_operario',
            name='requisitos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='operario.Requisitos_RS'),
        ),
    ]
