# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario_Nuevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('razon_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operario.Razon_Social')),
            ],
        ),
    ]
