# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-19 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0002_auto_20181219_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('requisitos_v', models.ManyToManyField(to='tecnico.Requisitos_Vehi')),
            ],
        ),
    ]
