# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-20 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0003_tipo_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_vehiculo',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
