# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-25 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0003_auto_20190723_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo_nuevo',
            name='en_tramite',
            field=models.BooleanField(default=True),
        ),
    ]
