# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-25 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0004_vehiculo_nuevo_en_tramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador_nuevo',
            name='renovando',
            field=models.BooleanField(default=False),
        ),
    ]
