# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0004_auto_20181220_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cumple', models.BooleanField(default=True)),
                ('requisitos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='tecnico.Requisitos_Vehi')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo_Nuevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(blank=True, max_length=75, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('checklist', models.ManyToManyField(related_name='vehiculo', through='tecnico.Checklist_Vehiculo', to='tecnico.Requisitos_Vehi')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operario_Nuevo')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Tipo_Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='checklist_vehiculo',
            name='vehiculo_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_vehiculo', to='tecnico.Vehiculo_Nuevo'),
        ),
    ]
