# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0006_operario_nuevo_vigente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe_Observados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField()),
                ('nombre_ente', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_ente', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_repr', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nota', models.CharField(blank=True, max_length=25, null=True)),
                ('cite_nota', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
