# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0008_informe_observados_operario_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisitos_vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tecnico_tipo_vehiculo_requisitos_v',
                'managed': False,
            },
        ),
    ]
