# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-09 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0010_requisitos_vehiculo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField()),
                ('nombre_ente', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_ente', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_repr', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta_solicitada', models.TextField(blank=True, null=True)),
                ('cantidad_tarjetas', models.IntegerField(blank=True, null=True)),
                ('operario_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operario_Nuevo')),
            ],
        ),
        migrations.RemoveField(
            model_name='informe_observados',
            name='operario_n',
        ),
        migrations.DeleteModel(
            name='Informe_Observados',
        ),
    ]
