# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-10 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operario', '0003_requisitos_razon_social'),
        ('tecnico', '0011_auto_20190109_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador_Nuevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('es_nuevo', models.BooleanField(default=True)),
                ('numero_registro', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=12, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('nit', models.CharField(blank=True, max_length=12, null=True)),
                ('ruta', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('documento_legal', models.TextField(blank=True, null=True)),
                ('digital', models.FileField(blank=True, null=True, upload_to='legal')),
            ],
        ),
        migrations.RemoveField(
            model_name='operario_nuevo',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='operario_nuevo',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='checklist_operario',
            name='operario_nuevo',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='operario_n',
        ),
        migrations.RemoveField(
            model_name='vehiculo_nuevo',
            name='operario',
        ),
        migrations.DeleteModel(
            name='Operario_Nuevo',
        ),
        migrations.AddField(
            model_name='operador_nuevo',
            name='checklist',
            field=models.ManyToManyField(related_name='operario', through='tecnico.Checklist_Operario', to='operario.Requisitos_RS'),
        ),
        migrations.AddField(
            model_name='operador_nuevo',
            name='razon_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operario.Razon_Social'),
        ),
        migrations.AddField(
            model_name='checklist_operario',
            name='operador_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_operario', to='tecnico.Operador_Nuevo'),
        ),
        migrations.AddField(
            model_name='nota',
            name='operador_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo'),
        ),
        migrations.AddField(
            model_name='vehiculo_nuevo',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo'),
        ),
    ]
