# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-14 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0012_auto_20190110_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='fotos-vehiculos')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Vehiculo_Nuevo')),
            ],
        ),
    ]
