# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-15 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0013_fotos_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos_vehiculo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tecnico.Vehiculo_Nuevo'),
        ),
    ]
