# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-18 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0014_auto_20190114_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Informe')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo')),
            ],
        ),
    ]
