# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-24 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0016_auto_20190123_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
