# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-30 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0017_auto_20190123_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs_Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo')),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo_nuevo',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='tecnico.Operador_Nuevo'),
        ),
    ]
