# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-11 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0021_auto_20190211_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo_nuevo',
            name='es_nuevo',
            field=models.BooleanField(default=True),
        ),
    ]
