# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-13 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0022_vehiculo_nuevo_es_nuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operador_nuevo',
            name='ruta',
        ),
    ]
