# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-13 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0023_remove_operador_nuevo_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(blank=True, max_length=100, null=True)),
                ('hora', models.CharField(blank=True, max_length=100, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Operador_Nuevo')),
            ],
        ),
    ]
