# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0025_auto_20190217_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='ans_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
