# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-28 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0026_informe_ans_tecnico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo_nuevo',
            old_name='capasidad',
            new_name='capacidad',
        ),
    ]
