# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0027_auto_20190228_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='concluciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
