# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0028_informe_concluciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
