# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0030_operador_nuevo_renovando'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador_nuevo',
            name='en_tramite',
            field=models.BooleanField(default=True),
        ),
    ]
