# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-21 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0031_operador_nuevo_en_tramite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operador_nuevo',
            name='renovando',
        ),
    ]
