# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-21 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0032_remove_operador_nuevo_renovando'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='fenecio',
            field=models.BooleanField(default=False),
        ),
    ]
