# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-26 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0035_checklist_vehiculo_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
