# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-28 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0036_informe_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs_legal',
            name='cite',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='docs_legal',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docs_legal',
            name='numero_ra',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
