# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-28 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0037_auto_20190328_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs_legal',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
