# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-11 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0038_docs_legal_vigente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs_legal',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
