# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-11 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0039_auto_20190411_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo', models.TextField(blank=True, default='EXTENSION DE TARJETAS DE OPERACIONES', null=True)),
                ('observacion', models.TextField(blank=True, default='EXTENSION DE TARJETAS DE OPERACIONES', null=True)),
                ('licencia', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.Vehiculo_Nuevo')),
            ],
        ),
    ]
