# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-11 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0040_infraccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
