# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0041_auto_20190411_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo_nuevo',
            name='dar_baja',
            field=models.BooleanField(default=False),
        ),
    ]
