# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-16 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0042_vehiculo_nuevo_dar_baja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='hora_i',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='hora_v',
            new_name='ruta',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='ruta_i',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='ruta_v',
        ),
    ]
