# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-04 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0043_auto_20190416_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs_legal',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 5, 4)),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 5, 4)),
        ),
    ]
