# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-05 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0045_auto_20190504_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs_legal',
            options={'permissions': (('administrar_doc_legal', 'Puede administrar documentos legales'),)},
        ),
    ]
