# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-06 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0046_auto_20190504_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operador_nuevo',
            options={'permissions': (('administrar_operador', 'Puede administrar al operador'), ('verificar', 'Puede verificar'))},
        ),
        migrations.AlterModelOptions(
            name='vehiculo_nuevo',
            options={'permissions': (('emitir_infraccion', 'Puede emitir infraccion'),)},
        ),
        migrations.AlterField(
            model_name='docs_legal',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 5, 6)),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 5, 6)),
        ),
    ]
