# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-06 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0047_auto_20190506_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operador_nuevo',
            options={'permissions': (('administrar_operador', 'Puede administrar al operador'), ('verificar', 'Puede verificar'), ('administrador', 'Puede administrar todo'))},
        ),
    ]
