# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-10 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0048_auto_20190506_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs_legal',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
