# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-11 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0050_auto_20190510_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs_legal',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 22, 37, 10, 270000)),
        ),
    ]
