# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-11 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0052_auto_20190510_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs_legal',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
